workflows:
  build:
    name: Build APK
    max_build_duration: 15
    environment:
      vars:
        NODE_ENV: production
    scripts:
      - npm install
      - cd android
      - chmod +x gradlew
      - .gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
