workflows:
  android-release:
    name: Android Release Build
    scripts:
      - npm install
      - chmod +x gradlew
      - ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
