workflows:
 android-no-wrapper:
    name: Android Build Without Gradle Wrapper
    max_build_duration: 60
    environment:
      node: 18
      java: 17
    scripts:
      - npm install
      - cd android
      - gradle assembleRelease
    artifacts:
      - android/app/build/outputs/release/*.apk
