workflows:
  build:
    name: Build APK
    max_build_duration: 15
    environment:
      vars:
        PACKAGE_NAME: "com.chargingtimer"
      node: 18.16.0
      java: 17
    scripts:
      - npm install
      - cd android
      - gradle assembleRelease
    artifacts:
      - android/app/build/outputs/release/*.apk
