workflows:
  build:
    name: Build APK
    max_build_duration: 15
    environment:
      vars:
        PACKAGE_NAME: "com.chargingtimer"
      node: 18.16.0
      java: 17
      android: sdk
    scripts:
      - npm install
      - cd android && chmod +x gradlew
      - ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
